# Generated by Django 3.1.3 on 2021-03-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210217_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
        migrations.CreateModel(
            name='PostBuyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, verbose_name='購入情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel', verbose_name='購入記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
